"use client";
import { useFormWithServerAction } from "@/hooks/useFormWithServerAction";
import { useState, useEffect } from "react";
import addUser from "../_actions/addUser";
import addUserSchema, {
  addUserErrorMapClient,
  AddUserInput,
} from "../_schemas/addUserSchema";
import { Plus, Shuffle } from "lucide-react";
import FormModal from "@/app/_components/forms/FormModal";
import FormField from "@/app/_components/forms/FormField";
import { UploadForm } from "@/app/_components/AS3UploadForm";

// Random data generators
const FIRST_NAMES = [
  "Giorgi",
  "Nino",
  "Davit",
  "Mariam",
  "Luka",
  "Ana",
  "Nikoloz",
  "Tamari",
  "Sandro",
  "Elene",
  "Irakli",
  "Salome",
  "Tornike",
  "Natia",
  "Giga",
  "Maka",
  "Levan",
  "Keti",
  "Nika",
  "Sopho",
];
const LAST_NAMES = [
  "Beridze",
  "Kapanadze",
  "Gelashvili",
  "Lomidze",
  "Maisuradze",
  "Tsiklauri",
  "Goglidze",
  "Khachidze",
  "Javakhishvili",
  "Chikhladze",
  "Dundua",
  "Gabashvili",
  "Ninidze",
  "Kvaratskhelia",
];
const BIOS = [
  "Love traveling and meeting new people!",
  "Student at TSU. Always looking for affordable rides.",
  "Working professional, prefer quiet rides.",
  "Frequent traveler between cities.",
  "Music lover, don't mind sharing playlists!",
  "",
];

// Background colors for avatars
const AVATAR_COLORS = [
  "3B82F6", // blue
  "10B981", // green
  "F59E0B", // amber
  "EF4444", // red
  "8B5CF6", // violet
  "EC4899", // pink
  "06B6D4", // cyan
  "F97316", // orange
];

function generateRandomData(): AddUserInput {
  const firstName = FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)];
  const lastName = LAST_NAMES[Math.floor(Math.random() * LAST_NAMES.length)];
  const randomId = Math.random().toString(36).substring(2, 8);
  const bgColor = AVATAR_COLORS[Math.floor(Math.random() * AVATAR_COLORS.length)];
  
  const name = `${firstName} ${lastName}`;
  // Generate avatar URL with initials
  const avatarUrl = `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bgColor}&color=fff&size=200&bold=true`;

  return {
    name,
    email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}.${randomId}@gmail.com`,
    mobileNumber: `+995 5${Math.floor(Math.random() * 100)
      .toString()
      .padStart(2, "0")} ${Math.floor(Math.random() * 1000)
      .toString()
      .padStart(3, "0")} ${Math.floor(Math.random() * 1000)
      .toString()
      .padStart(3, "0")}`,
    bio: BIOS[Math.floor(Math.random() * BIOS.length)],
    sex: (["MAN", "WOMAN"] as const)[Math.floor(Math.random() * 2)],
    profileImg: avatarUrl,
  };
}

export default function AddUserButton() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const { form, clientErrors, handleSubmit, loading, firstError, reset } =
    useFormWithServerAction(
      addUser,
      addUserSchema,
      addUserErrorMapClient,
      generateRandomData(),
      {
        onSuccess: () => {
          setIsModalOpen(false);
          reset();
        },
        onError: (_, err) => {
          console.error(err);
        },
        showErrorToast: true,
        showSuccessToast: true,
      }
    );

  const { register, setValue, watch } = form;
  const profileImg = watch("profileImg");
  const name = watch("name");

  // Check if current image is auto-generated (ui-avatars.com)
  const isAutoGeneratedAvatar = profileImg?.includes("ui-avatars.com");

  // Update avatar when name changes (only if using auto-generated avatar)
  useEffect(() => {
    if (name && isAutoGeneratedAvatar) {
      const bgColor = AVATAR_COLORS[Math.floor(Math.random() * AVATAR_COLORS.length)];
      const avatarUrl = `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bgColor}&color=fff&size=200&bold=true`;
      setValue("profileImg", avatarUrl);
    }
  }, [name, isAutoGeneratedAvatar, setValue]);

  const handleCloseModal = () => {
    setIsModalOpen(false);
    reset();
  };

  const fillRandomData = () => {
    const data = generateRandomData();
    Object.entries(data).forEach(([key, value]) => {
      setValue(key as keyof AddUserInput, value as never);
    });
  };

  return (
    <>
      <button
        type="button"
        onClick={() => setIsModalOpen(true)}
        className="px-4 py-2 bg-primary text-white rounded-md hover:bg-primary/90 flex items-center gap-2"
      >
        <Plus className="w-4 h-4" />
        Add User to Pool
      </button>

      {isModalOpen && (
        <FormModal
          title="Add Fake User"
          isOpen={isModalOpen}
          onClose={handleCloseModal}
          onSubmit={handleSubmit}
          loading={loading}
          firstError={firstError}
        >
          {/* Randomize Button */}
          <div className="flex justify-end mb-2">
            <button
              type="button"
              onClick={fillRandomData}
              className="text-sm px-3 py-1.5 text-gray-600 hover:text-primary hover:bg-primary/10 rounded-md flex items-center gap-1.5 transition-colors"
            >
              <Shuffle className="w-3.5 h-3.5" />
              Randomize
            </button>
          </div>

          <div className="space-y-3">
            {/* Profile Image */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Profile Image
              </label>
              <div className="flex items-center gap-4">
                {/* Current avatar preview */}
                <div className="relative">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={profileImg || "/default-pfp.jpg"}
                    alt="Avatar preview"
                    className="w-20 h-20 rounded-full object-cover border-2 border-primary"
                  />
                  {isAutoGeneratedAvatar && (
                    <span className="absolute -bottom-1 -right-1 bg-primary text-white text-xs px-1.5 py-0.5 rounded-full">
                      Auto
                    </span>
                  )}
                </div>
                
                {/* Upload custom */}
                <div className="flex flex-col gap-2">
                  <UploadForm
                    folderName="user-pool-profiles"
                    onSuccessfulUpload={(url) => setValue("profileImg", url)}
                    className="w-16 h-16 rounded-lg"
                    cropSize={{ width: 200, height: 200 }}
                  />
                  <span className="text-xs text-gray-500">
                    Or upload custom
                  </span>
                </div>
              </div>
              {clientErrors.profileImg && (
                <p className="text-red-500 text-sm mt-1">
                  {clientErrors.profileImg}
                </p>
              )}
            </div>

            <FormField
              label="Name"
              error={clientErrors.name}
              input={
                <input
                  {...register("name")}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="John Doe"
                />
              }
            />

            <FormField
              label="Email"
              error={clientErrors.email}
              input={
                <input
                  {...register("email")}
                  type="email"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="user@example.com"
                />
              }
            />

            <FormField
              label="Mobile Number"
              error={clientErrors.mobileNumber}
              input={
                <input
                  {...register("mobileNumber")}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="+995 555 123 456"
                />
              }
            />

            <FormField
              label="Sex"
              error={clientErrors.sex}
              input={
                <select
                  {...register("sex")}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                >
                  <option value="MAN">Man</option>
                  <option value="WOMAN">Woman</option>
                  <option value="OTHER">Other</option>
                </select>
              }
            />

            <FormField
              label="Bio (Optional)"
              error={clientErrors.bio}
              input={
                <textarea
                  {...register("bio")}
                  rows={2}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="Tell us about yourself..."
                />
              }
            />
          </div>
        </FormModal>
      )}
    </>
  );
}
